### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by WeissShahaf** [PeyracheLab/pynacollada#19]
error while trying to install on win10/miniconda:

(base) H:\pynacollada>pip install -e .
Obtaining file:///H:/pynacollada
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "H:\pynacollada\setup.py", line 9, in <module>
          readme = readme_file.read()
        File "C:\ProgramData\Miniconda3\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 16: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Tonisound** [comment]
Same issue here.
Using Windows 10 Pro.
